### PR TITLE
Update on quota logic

### PR DESCRIPTION
**Pull request by z0ne323**
- Update Script #12
- Update on quota logic

### CODE REVIEW

**Comment by nigleweber** [comment]
@v3r1t4s You've been busy I see. I've got a lot of comments for this PR.


### What looks good
1. Comments are looking 10/10
2. Return are looking much better
3. Function argumets are looking better as well
4. Load json function

### Remaining Work
1. What type is "malicious" in `data_processing`? You treat it as both a boolean and an int. Python will accept this, but it's poor coding style
2. In `handle_file` where if `file_arg` coming from? I'm super confused about how python let you do this.
3. JSON output
4. Move helpers to Helper.py
5. You have a magic string on line 276. Take it out of the call and assign it to a variable, then pass it to the function
6. Variable name does not match function `number_of_arguments_to_check` on line 292. Renamed to match what's passed to that function `nb_requests_user_want`
7. Recommended: convert `nb` to `num`. `num` is industry standard shorthand.
8. We need to reduce the number of file writes to 1 per file. 


### Questions
1. Why did start checking_quota?
2. Since you did, why do you still have an error case in the middle of searching file/ip data? 
3. Would this be better as a cmdline soft error and avoid writing to file?

**Comment by nigleweber** [comment]
## Refactor
I notice you are balancing a lot of things in your data_processing, file_handler and handle_file_report. First of all, if you expect to make 2 API calls per item, you should always have at least that many. This will save you from generating an incomplete report.


Try this on for size. It's untested and slightly pseudo code so you'll need to iron it out some.
```




def get_vt_data(api_key, string_argument):
  search_response = search_api_request(api_key, string_argument)
  if search_response is None:
    report_dic.append("[-] The search response we got had errors.")
    return "", ""
  response_file_reputation = file_reputation_api_request(api_key, string_argument)
  if response_file_reputation is None:
    report_dic.append("[-] The file reputation response we got had errors.")
    return "", ""
return search_response, response_file_reputation

~def handle_file_report(report_dic, string_argument, quota, file_argument, last_element):~
def create_report(report_dic, string_argument, quota, file_argument)
    """Function used to handle our file report"""
  print(f"---------------------------------\n[*] Working on {string_argument}\n")

  nb_of_request = 2
  if check_quota(quota, nb_of_request) is None:
    report_dic.append("[-] We've run out of quota'")
    return 0, report_dic
  search_response, reputation_response = get_vt_data(api_key, string_argument)

  response_dictionary = load_json(search_response)
  parse_json_error, analysis_stat = parse_vt_response(response_dictionary)
  if parse_json_error == 0:
    call_to_file_reputation, report_dic = data_processing(string_argument, response_dictionary, analysis_stat, report_dic)
    if call_to_file_reputation == 1:
      response_file_reputation = load_json(reputation_response)
      report_dic.append(f"[+] Getting you data of the file reputation response we got for {string_argument}:\n[*] The type_description of the hash is : {response_file_reputation['data']['attributes']['type_description']}\n[*] The hash was provided to VirusTotal by {str(response_file_reputation['data']['attributes']['unique_sources'])} unique sources\n[*] The most meaningful name of the hash file found by VirusTotal is: {response_file_reputation['data']['attributes']['meaningful_name']}\n[-] Check this link for more infos on your file: https://www.virustotal.com/gui/file/{string_argument}")
  return 0, report_dic



def handle_file(quota, file_arg):
  get_userinput()
  report_dictionary = []
  if file_arg:
    data_list=args.file.readlines()
    for d in data_list:
      error, report_dic = handle_file_report(report_dic, d, quota, file_arg)
        if error == 1:
          return 1
  else:
    error, report_dic = handle_file_report(report_dic,  args.string, quota, file_arg, True)
    if error == 1:
      return 1
  return report_dictionary



def main():
    ...
    report = handle_file(quota, file_arg)
    write_to_file(report)
```

**Comment by v3r1t4s** [comment]
> @v3r1t4s You've been busy I see. I've got a lot of comments for this PR.
> 
> ### What looks good
> 1. Comments are looking 10/10
> 2. Return are looking much better
> 3. Function argumets are looking better as well
> 4. Load json function
> 
> ### Remaining Work
> 1. What type is "malicious" in `data_processing`? You treat it as both a boolean and an int. Python will accept this, but it's poor coding style
> 2. In `handle_file` where if `file_arg` coming from? I'm super confused about how python let you do this.
> 3. JSON output
> 4. Move helpers to Helper.py
> 5. You have a magic string on line 276. Take it out of the call and assign it to a variable, then pass it to the function
> 6. Variable name does not match function `number_of_arguments_to_check` on line 292. Renamed to match what's passed to that function `nb_requests_user_want`
> 7. Recommended: convert `nb` to `num`. `num` is industry standard shorthand.
> 8. We need to reduce the number of file writes to 1 per file.
> 
> ### Questions
> 1. Why did start checking_quota?
> 2. Since you did, why do you still have an error case in the middle of searching file/ip data?
> 3. Would this be better as a cmdline soft error and avoid writing to file?

**Comment by z0ne323** [comment]
@nigleweber 
To respond to your comments:

I started checking_quota because even if I'm having error handling when I am querying the API with search_request and the file_reputation one, well technically it's unnecessary to really start all logic of the program if I don't even have the quota available to make my program run. So basically I run into this scenario of not having quota two days ago and I just had error, but I couldn't even figure it out how many requests I made how long should I wait etc (because the logic of the quota is explained nowhere you need to dig the API to know like okay did I hit the limit cap of the hour? The day? the month?) So yeah, technically we could totally remove the entire quota code and the program will run perfectly but the user if he exceeds the quota will basically have HTTP error 429, quota exceed. He won't know anything whereas the piece of code 1) save running all the logic for nothing since one of the first tasks is check the quota and 2) give more inside of okay the user reach the quota but how long does the user have to wait? Actually, I run into this situation my quota for the hour wasn't reached but I used all the quota for the day, so I didn't know before writing this piece that indeed it's not 4 per minutes its not x per hours I need to wait until next day at midnight UTC. Anyway, that's it for the why check quota. 

For why I still have an error case in the middle of the code (I guess you're talking about line 113 or around those lines.?) Well like I said I think in the comments I wanted to maximise the usage of the quota so I had to implement a logic in case of the user have enough quota to search the api but not enough to maybe check file_reputation, the problem is that a lot of code had to been added to take care of EVERY scenario. Like okay what if the user input a string, a file, what if it's the last argument of the file and not every argument of the file of the string will need two request etc  etc. But since like you said in your third question and also the second comments, I mean you seems to be more on the we should, overpredict how many request we will need to do (basically multiply by 2 potential nb_of_requests) I mean I already talked a little bit about this on the email like different possibility to fix the issue but we can totally take the safe path predicting that yeah every argument given to the program will need at lease *2 api query and this way don't have weird report without file reputation and also no really complicated too long code...

So yup anyway when the next update will be ready, I'll close this PR as always and you'll be able to either write here or write on the new one, as you want !

**Comment by z0ne323** [comment]
@nigleweber  my bad I should maybe answer a few things in the instructions for the code. Technically even though malicious seems to be binary with how it's written with if, technically it's probably just a int. Because at line 66 you can see that the variable is not set as True or False and what I'm querying is certainly not linked to a bool. Basically, you can totally use `if variable:` like the variable was a bool but the program never ever treats the variable as a bool just check if the thing is 0 or positive value (wait now that I'm saying this it doesnt sound like a bool operations, but not really a bool itself).
to let you check save this in a python file and see for yourself, python always consider this as an int
```py
malicious = 3

if malicious:
    print(malicious, type(malicious))

malicious = 0

if malicious:
    print(malicious, type(malicious))
else:
    print("NOPE")
````

but on the other hand, it might be very confusing so really separate both might be a good thing to do so everyone totally know that var A is a "bool" and var B is use to count how many times we got into the if scenario...

**Comment by z0ne323** [comment]
for the second instruction after malicious you can test and also read this code I guess
```py
def myfunction():
    print(global_variable)

if __name__ == '__main__':
    global_variable = 1            # Every function can access this one since it's a global one, 
                                   # Using if __name__ == '__main__': don't change the fact that every 
                                   # variable written outside of a function won't have a local but a global scope!

    myfunction()
```
but again confusing as hell for people so maybe if I'm putting it as a function argument everyone will understand OR we can go all the way and remove some function argument since a lot of useful global variable (like api_key) are used by the functions through arguments that we try to pass, but technically those can totally be accessible globally since they are on the main part of code, so we won't have to pass it to everyone.


EDIT: I totally forgot but if you're printing, making  a condition with if etc, it's pretty okay to access it outside of the main, the problem is if you're calling a function and the argument is the same name as a variable in the global scope it might think that you're trying to modify a global variable in your local scope and this will cause problem so basically if you only print something or using if etc no problem to do this but as you want.
(With api_key variable for example I can't use it outside of main to modify it, I need to call it in order to have no errors/ future problems, actually you've done this in your code (global variable usage without a proper arguments in the function) check for api_key in the code you put on the second comment we need to have it in our function arguments to use it!). But yup this thing won't work, and you'll see in next PR I'll need to add api key to the arguments functions to use it in get_vt_data for example....

**Comment by z0ne323** [comment]
I already showed you what I was doing in output and what I'll prefer to do related to this output on the email, what should we do about JSON output?

**Pull request merged**
